export const vendorCategories = [
  { value: "photographers", label: "Photographers" },
  { value: "makeup-artists", label: "Makeup Artists" },
  { value: "wedding-planners", label: "Wedding Planners" },
  { value: "caterers", label: "Caterers" },
  { value: "decorators", label: "Decorators" },
  { value: "djs", label: "DJs & Music" },
  { value: "venues", label: "Venues" },
  { value: "mehndi-artists", label: "Mehndi Artists" },
  { value: "bridal-wear", label: "Bridal Wear" },
  { value: "groom-wear", label: "Groom Wear" },
  { value: "invitation-cards", label: "Invitation Cards" },
];

export const districts = [
  { value: "chennai", label: "Chennai" },
  { value: "coimbatore", label: "Coimbatore" },
  { value: "madurai", label: "Madurai" },
  { value: "tiruchirappalli", label: "Tiruchirappalli" },
  { value: "salem", label: "Salem" },
  { value: "tirunelveli", label: "Tirunelveli" },
  { value: "erode", label: "Erode" },
  { value: "vellore", label: "Vellore" },
  { value: "thoothukudi", label: "Thoothukudi" },
  { value: "dindigul", label: "Dindigul" },
  { value: "thanjavur", label: "Thanjavur" },
  { value: "karur", label: "Karur" },
  { value: "namakkal", label: "Namakkal" },
  { value: "nagapattinam", label: "Nagapattinam" },
  { value: "tiruppur", label: "Tiruppur" },
  { value: "kanyakumari", label: "kanyakumari" },
];
